### ISSUE TITLE
Ignoring the PIN entry prompts causes a call to hangup with an exception

### ISSUE THREAD

**Issue by bklang** [adhearsion/voicemail#24]
If a user attempts to change his PIN, but then does not actually enter anything during the PIN prompts, this exception is raised and the call is terminated.  The user should be either be reprompted, or the PIN input should fail and return the user to the previous menu.

```
[2014-01-28 12:42:29] TRACE Punchblock::Connection::XMPP: RECEIVING (presence) <presence from="a45657fc-885c-11e3-9cc1-cf2c2f0ed02e@10.90.90.142/prompt-16" to="ringrayo@10.90.90.142/freeswitch-dev.ringplus.net-4769" type="unavailable">
  <complete xmlns="urn:xmpp:rayo:ext:1">
    <noinput xmlns="urn:xmpp:rayo:input:complete:1"/>
  </complete>
</presence>
[2014-01-28 12:42:29] DEBUG AdhearsionASR::PromptBuilder: Ask completed with result #<AdhearsionASR::Result status=:noinput, confidence=nil, utterance=nil, interpretation=nil, nlsml=nil>
[2014-01-28 12:42:29] ERROR Adhearsion::Call: a45657fc-885c-11e3-9cc1-cf2c2f0ed02e@10.90.90.142: <NoMethodError> undefined method `size' for nil:NilClass
    /srv/apps/ringplus_core/shared/bundle/ruby/1.9.1/bundler/gems/voicemail-48959f952d3b/lib/voicemail/call_controllers/mailbox_set_pin_controller.rb:32:in `set_pin'
    /srv/apps/ringplus_core/shared/bundle/ruby/1.9.1/bundler/gems/voicemail-48959f952d3b/lib/voicemail/call_controllers/mailbox_set_pin_controller.rb:10:in `block (2 levels) in section_menu'
```

**Comment by emcgee** [comment]
This is now addressed in https://github.com/adhearsion/voicemail/pull/32
